<?php
echo '<!doctype html>';
echo '<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable" data-theme="default" data-theme-colors="default">';
echo '';
echo '';
echo '<head>';
echo '';
echo '<meta charset="utf-8" />';
echo '<title>Welcome | Pereine - CRM & Dashboard</title>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />';
echo '<meta content="Themesbrand" name="author" />';
echo '<!-- App favicon -->';
echo '<link rel="shortcut icon" href="../agc/pereine/velzon/assets/images/favicon.ico">';
echo '';
echo '<!-- Layout config Js -->';
echo '<script src="../agc/pereine/velzon/assets/js/layout.js"></script>';
echo '<!-- Bootstrap Css -->';
echo '<link href="../agc/pereine/velzon/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />';
echo '<!-- Icons Css -->';
echo '<link href="../agc/pereine/velzon/assets/css/icons.min.css" rel="stylesheet" type="text/css" />';
echo '<!-- App Css-->';
echo '<link href="../agc/pereine/velzon/assets/css/app.min.css" rel="stylesheet" type="text/css" />';
echo '<!-- custom Css-->';
echo '<link href="../agc/pereine/velzon/assets/css/custom.min.css" rel="stylesheet" type="text/css" />';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<!-- auth-page wrapper -->';
echo '<div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">';
echo '<div class="bg-overlay"></div>';
echo '<!-- auth-page content -->';
echo '<div class="auth-page-content overflow-hidden pt-lg-5">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="card overflow-hidden galaxy-border-none card-bg-fill">';
echo '<div class="row justify-content-center g-0">';
echo '<div class="col-lg-6">';
echo '<div class="p-lg-5 p-4 auth-one-bg h-100">';
echo '<div class="bg-overlay"></div>';
echo '<div class="position-relative h-100 d-flex flex-column">';
echo '<div class="mb-4">';
echo '<a href="index.html" class="d-block">';
echo '<img src="../agc/pereine/velzon/assets/images/logo-light.png" alt="" height="18">';
echo '</a>';
echo '</div>';
echo '<div class="mt-auto">';
echo '<div class="mb-3">';
echo '<i class="ri-double-quotes-l display-4 text-success"></i>';
echo '</div>';
echo '';
echo '<div id="qoutescarouselIndicators" class="carousel slide" data-bs-ride="carousel">';
echo '<div class="carousel-indicators">';
echo '<button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>';
echo '<button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>';
echo '<button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>';
echo '</div>';
echo '<div class="carousel-inner text-center text-white-50 pb-5">';
echo '<div class="carousel-item active">';
echo '<p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>';
echo '</div>';
echo '<div class="carousel-item">';
echo '<p class="fs-15 fst-italic">" The theme is really great with an amazing customer support."</p>';
echo '</div>';
echo '<div class="carousel-item">';
echo '<p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- end carousel -->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- end col -->';
echo '';
echo '<div class="col-lg-6">';
echo '<div class="p-lg-5 p-4">';
echo '<div>';
echo '<h5 class="text-primary">Welcome To Pereine CRM</h5>';
echo '<p class="text-muted">Enter your choice to enjoy our crm!</p>';
echo '</div>';
echo '<div class="user-thumb text-center">';
echo '<img src="./images/pereine-logo.jpeg" class="rounded-circle img-thumbnail avatar-lg material-shadow" alt="thumbnail">';
echo '<h5 class="mt-3">Pereine Soft</h5>';
echo '</div>';
echo '';
echo '<div class="mt-4">';
echo '<form>';
echo '<div class="mb-3">';
echo '<p><a class="btn btn-success w-100" href="../agc/vicidial.php" class="link-success link-offset-2 text-decoration-underline link-underline-opacity-25 link-underline-opacity-100-hover">Agent Login</a></p>';
echo '<p><a class="btn btn-info bg-gradient waves-effect waves-light w-100" href="../agc/timeclock.php?referrer=welcome"  class="link-success link-offset-2 text-decoration-underline link-underline-opacity-25 link-underline-opacity-100-hover">Timeclock</a></p>';
echo '<p><a class="btn btn-secondary bg-gradient waves-effect waves-light w-100" href="../vicidial/admin.php" class="link-success link-offset-2 text-decoration-underline link-underline-opacity-25 link-underline-opacity-100-hover">Administration</a></p>';
echo '</div>';
echo '<div class="mb-2 mt-4">';
echo '</div>';
echo '</form><!-- end form -->';
echo '</div>';
echo '';

echo '</div>';
echo '</div>';
echo '<!-- end col -->';
echo '</div>';
echo '<!-- end row -->';
echo '</div>';
echo '<!-- end card -->';
echo '</div>';
echo '<!-- end col -->';
echo '';
echo '</div>';
echo '<!-- end row -->';
echo '</div>';
echo '<!-- end container -->';
echo '</div>';
echo '<!-- end auth page content -->';
echo '';
echo '<!-- footer -->';
echo '<footer class="footer galaxy-border-none">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="text-center">';
echo '<p class="mb-0">&copy;';
echo '<script>document.write(new Date().getFullYear())</script> Dial Crm. Crafted with <i class="mdi mdi-heart text-danger"></i> by Pereine';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<!-- end Footer -->';
echo '</div>';
echo '<!-- end auth-page-wrapper -->';
echo '';
echo '<!-- JAVASCRIPT -->';
echo '<script src="../agc/pereine/velzon/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>';
echo '<script src="../agc/pereine/velzon/assets/libs/simplebar/simplebar.min.js"></script>';
echo '<script src="../agc/pereine/velzon/assets/libs/node-waves/waves.min.js"></script>';
echo '<script src="../agc/pereine/velzon/assets/libs/feather-icons/feather.min.js"></script>';
echo '<script src="../agc/pereine/velzon/assets/js/pages/plugins/lord-icon-2.1.0.js"></script>';
echo '<script src="../agc/pereine/velzon/assets/js/plugins.js"></script>';
echo '</body>';
echo '';
echo '';
echo '</html>';
?>